/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SpeakBuddy;

/**
 *
 * @author Carlos Alberto Alves Pereira
 */
public class ConText extends javax.swing.JFrame {

    /**
     * Creates new form ConText
     */
    public ConText() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        phonSymbTable = new javax.swing.JTabbedPane();
        consPanel = new javax.swing.JPanel();
        drinkLabel = new javax.swing.JLabel();
        drinkButton = new javax.swing.JButton();
        takeLabel = new javax.swing.JLabel();
        takeButton = new javax.swing.JButton();
        playLabel = new javax.swing.JLabel();
        playButton = new javax.swing.JButton();
        seeLabel = new javax.swing.JLabel();
        seeButton = new javax.swing.JButton();
        muchButton = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        helloLabel = new javax.swing.JLabel();
        helloButton = new javax.swing.JButton();
        ringLabel = new javax.swing.JLabel();
        ringButton = new javax.swing.JButton();
        zooLabel = new javax.swing.JLabel();
        zooButton = new javax.swing.JButton();
        VowPanel = new javax.swing.JPanel();
        carLabel = new javax.swing.JLabel();
        carButton = new javax.swing.JButton();
        catLabel = new javax.swing.JLabel();
        catButton = new javax.swing.JButton();
        agoLabel = new javax.swing.JLabel();
        agoButton = new javax.swing.JButton();
        footLabel = new javax.swing.JLabel();
        footButton = new javax.swing.JButton();
        furLabel = new javax.swing.JLabel();
        furButton = new javax.swing.JButton();
        bootLabel = new javax.swing.JButton();
        bootButton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Content Table - SpeakBuddy");
        setBackground(new java.awt.Color(255, 255, 255));

        phonSymbTable.setBackground(new java.awt.Color(255, 255, 255));

        consPanel.setBackground(new java.awt.Color(0, 153, 204));

        drinkLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/drink.png"))); // NOI18N
        drinkLabel.setText("jLabel1");

        drinkButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/audioButton.png"))); // NOI18N

        takeLabel.setBackground(new java.awt.Color(255, 255, 255));
        takeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/take.png"))); // NOI18N
        takeLabel.setText("jLabel1");

        takeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/audioButton.png"))); // NOI18N

        playLabel.setBackground(new java.awt.Color(255, 255, 255));
        playLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/play.png"))); // NOI18N
        playLabel.setText("jLabel1");

        playButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/audioButton.png"))); // NOI18N

        seeLabel.setBackground(new java.awt.Color(255, 255, 255));
        seeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/see.png"))); // NOI18N
        seeLabel.setText("jLabel1");

        seeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/audioButton.png"))); // NOI18N

        muchButton.setBackground(new java.awt.Color(255, 255, 255));
        muchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/much.png"))); // NOI18N
        muchButton.setText("jLabel1");

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/audioButton.png"))); // NOI18N

        helloLabel.setBackground(new java.awt.Color(255, 255, 255));
        helloLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/hello.png"))); // NOI18N
        helloLabel.setText("jLabel1");

        helloButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/audioButton.png"))); // NOI18N

        ringLabel.setBackground(new java.awt.Color(255, 255, 255));
        ringLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ring.png"))); // NOI18N

        ringButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/audioButton.png"))); // NOI18N

        zooLabel.setBackground(new java.awt.Color(255, 255, 255));
        zooLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/zoo.png"))); // NOI18N
        zooLabel.setText("jLabel1");

        zooButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/audioButton.png"))); // NOI18N

        javax.swing.GroupLayout consPanelLayout = new javax.swing.GroupLayout(consPanel);
        consPanel.setLayout(consPanelLayout);
        consPanelLayout.setHorizontalGroup(
            consPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consPanelLayout.createSequentialGroup()
                .addGroup(consPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(consPanelLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(drinkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(consPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(consPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(drinkLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ringLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(consPanelLayout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(consPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(seeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ringButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(65, 65, 65)
                .addGroup(consPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(consPanelLayout.createSequentialGroup()
                        .addGroup(consPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(takeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(muchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(consPanelLayout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(consPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(takeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(65, 65, 65)
                        .addGroup(consPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(playLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(helloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(consPanelLayout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(consPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(playButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(helloButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(39, Short.MAX_VALUE))
                    .addGroup(consPanelLayout.createSequentialGroup()
                        .addGroup(consPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(zooLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(consPanelLayout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(zooButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        consPanelLayout.setVerticalGroup(
            consPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(consPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(consPanelLayout.createSequentialGroup()
                        .addComponent(playLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(playButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(consPanelLayout.createSequentialGroup()
                        .addComponent(takeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(takeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(consPanelLayout.createSequentialGroup()
                        .addComponent(drinkLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(drinkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56)
                .addGroup(consPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(consPanelLayout.createSequentialGroup()
                        .addComponent(seeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(seeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(consPanelLayout.createSequentialGroup()
                        .addComponent(muchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(consPanelLayout.createSequentialGroup()
                        .addComponent(helloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(helloButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(consPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(consPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ringLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ringButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(consPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(zooLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(zooButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        phonSymbTable.addTab("Consonant Symbols", consPanel);

        VowPanel.setBackground(new java.awt.Color(0, 153, 204));

        carLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/car.png"))); // NOI18N

        carButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/audioButton.png"))); // NOI18N

        catLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cat.png"))); // NOI18N

        catButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/audioButton.png"))); // NOI18N

        agoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ago.png"))); // NOI18N

        agoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/audioButton.png"))); // NOI18N

        footLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/foot.png"))); // NOI18N

        footButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/audioButton.png"))); // NOI18N

        furLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fur.png"))); // NOI18N

        furButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/audioButton.png"))); // NOI18N

        bootLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/audioButton.png"))); // NOI18N

        bootButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/boot.png"))); // NOI18N

        javax.swing.GroupLayout VowPanelLayout = new javax.swing.GroupLayout(VowPanel);
        VowPanel.setLayout(VowPanelLayout);
        VowPanelLayout.setHorizontalGroup(
            VowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VowPanelLayout.createSequentialGroup()
                .addGroup(VowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VowPanelLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(carButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(VowPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(VowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(footLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(VowPanelLayout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(footButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(carLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(65, 65, 65)
                .addGroup(VowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(catLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bootButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(VowPanelLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(VowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(catButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bootLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(65, 65, 65)
                .addGroup(VowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(furLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(VowPanelLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(VowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(agoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(furButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        VowPanelLayout.setVerticalGroup(
            VowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VowPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(VowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(carLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(catLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(VowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(catButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(VowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VowPanelLayout.createSequentialGroup()
                        .addComponent(footLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(footButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(VowPanelLayout.createSequentialGroup()
                        .addComponent(furLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(furButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(VowPanelLayout.createSequentialGroup()
                        .addComponent(bootButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bootLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(215, Short.MAX_VALUE))
        );

        phonSymbTable.addTab("Vowel Symbols", VowPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(phonSymbTable)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(phonSymbTable)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel VowPanel;
    private javax.swing.JButton agoButton;
    private javax.swing.JLabel agoLabel;
    private javax.swing.JLabel bootButton;
    private javax.swing.JButton bootLabel;
    private javax.swing.JButton carButton;
    private javax.swing.JLabel carLabel;
    private javax.swing.JButton catButton;
    private javax.swing.JLabel catLabel;
    private javax.swing.JPanel consPanel;
    private javax.swing.JButton drinkButton;
    private javax.swing.JLabel drinkLabel;
    private javax.swing.JButton footButton;
    private javax.swing.JLabel footLabel;
    private javax.swing.JButton furButton;
    private javax.swing.JLabel furLabel;
    private javax.swing.JButton helloButton;
    private javax.swing.JLabel helloLabel;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel muchButton;
    private javax.swing.JTabbedPane phonSymbTable;
    private javax.swing.JButton playButton;
    private javax.swing.JLabel playLabel;
    private javax.swing.JButton ringButton;
    private javax.swing.JLabel ringLabel;
    private javax.swing.JButton seeButton;
    private javax.swing.JLabel seeLabel;
    private javax.swing.JButton takeButton;
    private javax.swing.JLabel takeLabel;
    private javax.swing.JButton zooButton;
    private javax.swing.JLabel zooLabel;
    // End of variables declaration//GEN-END:variables
}
