/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SpeakBuddy;

import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import javax.swing.JFrame;


import javax.swing.JOptionPane;
/**
 *
 * @author Carlos Alberto Alves Pereira
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    
    Storage storage;
    
    int n=0, selected;
    String name="";
    
    public MainScreen() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        Root = new javax.swing.JPanel();
        WCPanel = new javax.swing.JPanel();
        MSEnter = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CharChooser = new javax.swing.JPanel();
        CChooserNext = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        amyButton = new javax.swing.JButton();
        peterButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        HomePage = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        prev = new javax.swing.JButton();
        next = new javax.swing.JButton();
        recButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        mainMenu = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        recItem = new javax.swing.JMenuItem();
        myStuffMenu = new javax.swing.JMenu();
        myCharItem = new javax.swing.JMenuItem();
        recsItem = new javax.swing.JMenuItem();
        auxMenu = new javax.swing.JMenu();
        contItem = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        instItem = new javax.swing.JMenuItem();
        aboutItem = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("File");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SpeakBuddy");

        Root.setBackground(new java.awt.Color(0, 153, 204));
        Root.setLayout(new java.awt.CardLayout());

        WCPanel.setBackground(new java.awt.Color(0, 153, 204));

        MSEnter.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        MSEnter.setText("ENTER");
        MSEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MSEnterActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome to SpeakBuddy!");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Your simple tool for pronunciation practice");

        javax.swing.GroupLayout WCPanelLayout = new javax.swing.GroupLayout(WCPanel);
        WCPanel.setLayout(WCPanelLayout);
        WCPanelLayout.setHorizontalGroup(
            WCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WCPanelLayout.createSequentialGroup()
                .addContainerGap(260, Short.MAX_VALUE)
                .addGroup(WCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(MSEnter)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(277, 277, 277))
        );
        WCPanelLayout.setVerticalGroup(
            WCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WCPanelLayout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addComponent(MSEnter)
                .addContainerGap(263, Short.MAX_VALUE))
        );

        Root.add(WCPanel, "card5");

        CharChooser.setBackground(new java.awt.Color(0, 153, 204));

        CChooserNext.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        CChooserNext.setText("Next");
        CChooserNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CChooserNextActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Choose Your Character");

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        amyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Amy.png"))); // NOI18N
        amyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amyButtonActionPerformed(evt);
            }
        });

        peterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Peter.png"))); // NOI18N
        peterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peterButtonActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Amy");

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Peter");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(amyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(peterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(amyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(peterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CharChooserLayout = new javax.swing.GroupLayout(CharChooser);
        CharChooser.setLayout(CharChooserLayout);
        CharChooserLayout.setHorizontalGroup(
            CharChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CharChooserLayout.createSequentialGroup()
                .addContainerGap(281, Short.MAX_VALUE)
                .addGroup(CharChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(CChooserNext)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(223, 223, 223))
        );
        CharChooserLayout.setVerticalGroup(
            CharChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CharChooserLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel5)
                .addGap(90, 90, 90)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(CChooserNext)
                .addGap(115, 115, 115))
        );

        Root.add(CharChooser, "CharChooser");

        HomePage.setBackground(new java.awt.Color(0, 153, 204));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("jLabel6");

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("jLabel7");

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("jLabel8");

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("jLabel9");

        jPanel4.setBackground(new java.awt.Color(0, 153, 204));

        prev.setBackground(new java.awt.Color(255, 201, 14));
        prev.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        prev.setForeground(new java.awt.Color(51, 51, 51));
        prev.setText("<");
        prev.setEnabled(false);
        prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevActionPerformed(evt);
            }
        });

        next.setBackground(new java.awt.Color(255, 201, 14));
        next.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        next.setForeground(new java.awt.Color(51, 51, 51));
        next.setText(">");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(prev)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(next))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prev)
                    .addComponent(next))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        recButton.setBackground(new java.awt.Color(255, 201, 14));
        recButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        recButton.setForeground(new java.awt.Color(51, 51, 51));
        recButton.setText("Record");
        recButton.setVisible(false);
        recButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("jLabel3");

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));

        jLabel4.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout HomePageLayout = new javax.swing.GroupLayout(HomePage);
        HomePage.setLayout(HomePageLayout);
        HomePageLayout.setHorizontalGroup(
            HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePageLayout.createSequentialGroup()
                .addGap(355, 355, 355)
                .addComponent(recButton)
                .addContainerGap(393, Short.MAX_VALUE))
            .addGroup(HomePageLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        HomePageLayout.setVerticalGroup(
            HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePageLayout.createSequentialGroup()
                .addGroup(HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomePageLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(176, 176, 176))
                    .addGroup(HomePageLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(recButton)
                .addGap(90, 90, 90))
        );

        Root.add(HomePage, "IntroducingScreen");

        mainMenu.setBackground(new java.awt.Color(255, 255, 255));

        menuFile.setBackground(new java.awt.Color(255, 255, 255));
        menuFile.setText("File");
        menuFile.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N

        recItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        recItem.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        recItem.setText("New Recording");
        recItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recItemActionPerformed(evt);
            }
        });
        menuFile.add(recItem);

        myStuffMenu.setBackground(new java.awt.Color(255, 255, 255));
        myStuffMenu.setText("MyStuff");
        myStuffMenu.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N

        myCharItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        myCharItem.setBackground(new java.awt.Color(255, 255, 255));
        myCharItem.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        myCharItem.setText("My Character");
        myCharItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myCharItemActionPerformed(evt);
            }
        });
        myStuffMenu.add(myCharItem);

        recsItem.setBackground(new java.awt.Color(255, 255, 255));
        recsItem.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        recsItem.setText("Recordings");
        recsItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recsItemActionPerformed(evt);
            }
        });
        myStuffMenu.add(recsItem);

        menuFile.add(myStuffMenu);

        auxMenu.setBackground(new java.awt.Color(255, 255, 255));
        auxMenu.setText("Aux Content");
        auxMenu.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N

        contItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        contItem.setBackground(new java.awt.Color(255, 255, 255));
        contItem.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        contItem.setText("Content Table");
        contItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contItemActionPerformed(evt);
            }
        });
        auxMenu.add(contItem);

        menuFile.add(auxMenu);

        exit.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        menuFile.add(exit);

        mainMenu.add(menuFile);

        helpMenu.setBackground(new java.awt.Color(255, 255, 255));
        helpMenu.setText("Help");
        helpMenu.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N

        instItem.setBackground(new java.awt.Color(255, 255, 255));
        instItem.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        instItem.setText("Instructions");
        helpMenu.add(instItem);

        aboutItem.setBackground(new java.awt.Color(255, 255, 255));
        aboutItem.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        aboutItem.setText("About SpeakBuddy");
        helpMenu.add(aboutItem);

        mainMenu.add(helpMenu);

        setJMenuBar(mainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Root, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Root, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void showScreen(JFrame frame){
    frame.setVisible(true);
    frame.setLocationRelativeTo(null);
}
public void showLayout(String layout){
    CardLayout cardLayout = (CardLayout) Root.getLayout();
            cardLayout.show(Root, layout);
}
    private void myCharItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myCharItemActionPerformed
        showScreen(new Avatar());
    }//GEN-LAST:event_myCharItemActionPerformed

    private void contItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contItemActionPerformed
        showScreen(new ConText());
    }//GEN-LAST:event_contItemActionPerformed

    private void MSEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MSEnterActionPerformed
        try{
            storage=new Storage("Student");
            storage.readUserInfo();
            name=storage.linhas[0];
            
            showLayout("IntroducingScreen");
            new atualiza().start();
        }
        catch(IOException ie){
        showLayout("CharChooser");
        }
    }//GEN-LAST:event_MSEnterActionPerformed

    private void CChooserNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CChooserNextActionPerformed
        storage=new Storage("Student");
        
        if(selected==0){
           JOptionPane.showMessageDialog(null, "You must choose one of the characters!");
       }
       else{
                if(selected== 1){
                    name="Amy";
                }
       
                if(selected==2){
                    name="Peter";
                }
                try {
                    String []infor=new String[4];
                    infor[0]=name;
                    infor[1]=0+"";
                    infor[2]=1+"";
                    infor[3]=false+"";
                    storage.writeUserInfo(infor);
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
            showLayout("IntroducingScreen");
            new atualiza().start();
            }
       
    }//GEN-LAST:event_CChooserNextActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        n++;        
    }//GEN-LAST:event_nextActionPerformed

    private void prevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevActionPerformed
        if(n==4){
            n=n-2;
        }
        else{
             n--;
        }
    }//GEN-LAST:event_prevActionPerformed

    private void recButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recButtonActionPerformed
        showScreen(new CaptureScreen());
        n=4;
    }//GEN-LAST:event_recButtonActionPerformed

    private void amyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amyButtonActionPerformed
        peterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Peter.png")));
        amyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/AmySelected.png")));
        selected=1;
    }//GEN-LAST:event_amyButtonActionPerformed

    private void peterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peterButtonActionPerformed
        amyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Amy.png")));
        peterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/PeterSelected.png")));
        selected=2;
    }//GEN-LAST:event_peterButtonActionPerformed

    private void recItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recItemActionPerformed
        showScreen(new CaptureScreen());
        n=4;
    }//GEN-LAST:event_recItemActionPerformed

    private void recsItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recsItemActionPerformed
        String args[]=new String[0];
        String media = "./";
        final Juke juke = new Juke(args.length == 0 ? media : args[0]);
        juke.open();
        JFrame f = new JFrame("My Recordings - SpeakBuddy");
        f.addWindowListener(new WindowAdapter() {
            
            public void windowIconified(WindowEvent e) { 
                juke.credits.interrupt();
            }
        });
        f.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        f.getContentPane().add("Center", juke);
        f.pack();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int w = 750;
        int h = 340;
        f.setLocation(screenSize.width/2 - w/2, screenSize.height/2 - h/2);
        f.setSize(w, h);
        f.setResizable(false);
        f.setVisible(true);
        if (args.length > 0) {
            File file = new File(args[0]);
            if (file == null && !file.isDirectory()) {
                System.out.println("usage: java Juke audioDirectory");
            } 
        }
    }//GEN-LAST:event_recsItemActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed
    public class atualiza extends Thread{
    @Override
    public void run(){
       while(true){
                if(n==4){
                   try {
                       sleep(100);
                   } catch (InterruptedException ie) {
                       ie.printStackTrace();
                   }
                }
               if(n>=3){
                   recButton.setVisible(true);
               }
               if(n==0){
               jLabel6.setText("Hi! I'm "+name+" and I'm going to be your guide here.");
               jLabel7.setText("I hope we can become great friends!");
               jLabel8.setText("");
               jLabel9.setText("");
               jLabel3.setText("");
               next.setEnabled(true);
               prev.setEnabled(false);
               jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/"+name+"1.png")));
                }
               if(n==1){
               jLabel6.setText("Our goal:");
               jLabel7.setText("Here you can practice your pronunciation as much as you want,");
               jLabel8.setText("and by doing it, you also help me to grow up and reach higher levels!");
               jLabel9.setText("How? Every time you practice your pronunciation by recording yourself,");
               jLabel3.setText("your character will gain 50 points. How many points do you want to reach?");
               prev.setEnabled(true);
               jLabel9.setVisible(true);
               jLabel8.setVisible(true);
               jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/"+name+"2.png")));
               }
               if(n==2){
               jLabel6.setText("Ready to start recording?");
               jLabel7.setText("Maybe you want to practice your pronunciation first. We can help with it!");
               jLabel8.setText("Step 1: Click on 'File',");
               jLabel9.setText("Step 2: Go to 'Aux Content'");
               jLabel3.setText("Step 3: Click on 'Content Table'");
               jLabel3.setVisible(true);
               jLabel9.setVisible(true);
               next.setEnabled(true);
               
               }
               if(n==3){
                   jLabel6.setText("All set?! So let's get started!");
                   jLabel7.setText("");
                   jLabel8.setText("");
                    jLabel9.setText("");
                    jLabel3.setText("");
                    next.setEnabled(false);
                    jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/"+name+"3.png")));
               }    
       } 
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CChooserNext;
    private javax.swing.JPanel CharChooser;
    private javax.swing.JPanel HomePage;
    private javax.swing.JButton MSEnter;
    private javax.swing.JPanel Root;
    private javax.swing.JPanel WCPanel;
    private javax.swing.JMenuItem aboutItem;
    private javax.swing.JButton amyButton;
    private javax.swing.JMenu auxMenu;
    private javax.swing.JMenuItem contItem;
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem instItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JMenuBar mainMenu;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem myCharItem;
    private javax.swing.JMenu myStuffMenu;
    private javax.swing.JButton next;
    private javax.swing.JButton peterButton;
    private javax.swing.JButton prev;
    private javax.swing.JButton recButton;
    private javax.swing.JMenuItem recItem;
    private javax.swing.JMenuItem recsItem;
    // End of variables declaration//GEN-END:variables
}
